import React, { useEffect, useMemo, useState } from "react";
import { initializeApp } from "firebase/app";
import { doc, getDoc, getFirestore, serverTimestamp, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyC1t9oLmiJetV3MerHOyatS73-veYLpGsQ",
  authDomain: "srna-planner.firebaseapp.com",
  projectId: "srna-planner",
  storageBucket: "srna-planner.firebasestorage.app",
  messagingSenderId: "426686173226",
  appId: "1:426686173226:web:dbeca561ff2b40d9ed3353",
  measurementId: "G-KN2ZGN4914",
};

const firebaseApp = initializeApp(firebaseConfig);
const db = getFirestore(firebaseApp);
const PLANNER_DOC_REF = doc(db, "planners", "alyssa-summer-2026");

const clinicalSchedule = {
  May: { 12: ["🩺 Clinical"], 13: ["🩺 Clinical"], 19: ["🩺 Clinical"], 20: ["🩺 Clinical"], 26: ["🩺 Clinical"], 27: ["🩺 Clinical"] },
  June: { 2: ["🩺 Clinical"], 3: ["🩺 Clinical"], 11: ["🩺 Clinical"], 12: ["🩺 Clinical"], 18: ["🩺 Clinical"], 19: ["🩺 Clinical"], 25: ["🩺 Clinical"], 26: ["🩺 Clinical"] },
  July: { 7: ["🩺 Clinical"], 8: ["🩺 Clinical"], 14: ["🩺 Clinical"], 15: ["🩺 Clinical"], 21: ["🩺 Clinical"], 22: ["🩺 Clinical"], 30: ["🩺 Clinical"], 31: ["🩺 Clinical"] },
  August: { 6: ["🩺 Clinical"], 7: ["🩺 Clinical"], 13: ["🩺 Clinical"], 14: ["🩺 Clinical"] },
};

const monthlyCalendarData = {
  May: { color: "from-rose-100 to-pink-50", accent: "text-rose-300", events: { 15: ["Seminar Intro DB", "Clinical Syllabus Attestation"], 17: ["SIM Syllabus Review Attestation"], 18: ["Seminar Syllabus Quiz", "Principles 2 Plan for Success", "Clinical Airway Anatomy WB"], 20: ["Systems Intro DB", "SIM Optional: Adductor/Popliteal"], 22: ["Systems Assignment 1"], 23: ["Systems DB 1"], 25: ["Clinical Week 2: 2 evals + 2 care plans"], 26: ["Plagiarism Attestation Quiz"], 30: ["Systems DB Replies"] } },
  June: { color: "from-violet-100 to-purple-50", accent: "text-violet-300", events: { 1: ["Clinical Respiratory Physiology WB", "2 evals + 2 care plans", "Seminar Presentation 1 week"], 3: ["SIM Optional: LAST/Pneumo/Machine Failure"], 6: ["Systems DB 2"], 8: ["Principles 2 Exam 1", "Clinical Respiratory Pathophys WB", "2 evals + 2 care plans"], 13: ["Systems DB Replies"], 15: ["Seminar Presentation 2 week", "Clinical Airway Management WB", "2 evals + 2 care plans", "Journal Club TBD"], 22: ["Clinical Cell Communication WB", "Comprehensive Care Plan #1", "2 evals + 2 care plans", "SIM Test-Out Week"], 24: ["Mandatory SIM Test-Out Class"], 25: ["Mandatory SIM Test-Out Class"], 29: ["Seminar Presentation 3 week"] } },
  July: { color: "from-red-100 to-orange-50", accent: "text-red-300", events: { 2: ["SIM Bronchospasm/Anaphylaxis Quiz"], 3: ["School Closed"], 6: ["Clinical ANS A&P WB", "2 evals + 2 care plans", "Summative + site/preceptor evals"], 9: ["SIM Hypoxia Quiz"], 11: ["Systems DB 3 — no peer replies"], 13: ["Principles 2 AP2 Exam 2", "Clinical ANS Pharm & Patho WB", "2 evals + 2 care plans", "Seminar Quiz 1 week"], 19: ["SIM DB #1"], 20: ["Clinical CV Anatomy & Physiology WB", "2 evals + 2 care plans", "Seminar Franciscan Values Paper", "Seminar Presentation 4 week"], 25: ["Systems Assignment 2"], 27: ["Clinical Valvular Heart Dz WB", "2 evals + 2 care plans", "Journal Club TBD"] } },
  August: { color: "from-blue-100 to-cyan-50", accent: "text-blue-300", events: { 2: ["SIM DB #2"], 3: ["Clinical CV Pathophys WB", "2 evals + 2 care plans", "Seminar Presentation 5 week"], 10: ["Principles 2 Exam 3", "Clinical Comprehensive Care Plan #2", "2 evals + 2 care plans", "Seminar Quiz 2 week"], 11: ["Systems Professional Practice Paper"], 17: ["Finals Week", "Principles 2 AP2 Final Exam", "Clinical Make-Up Week", "Summative + site/preceptor evals"] } },
};

const calendarMonths = [ { name: "May", days: 31, start: 5 }, { name: "June", days: 30, start: 1 }, { name: "July", days: 31, start: 3 }, { name: "August", days: 31, start: 6 } ];
const weekdayHeaders = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const weeklySchedule = [
  { week: "Week of 5/11", focus: "Semester setup + early attestations", tasks: ["5/15 — Seminar Intro Discussion Board", "5/15 — Clinical Syllabus Attestation", "5/17 — SIM Syllabus Review Attestation", "5/18 — Seminar Syllabus Attestation Quiz", "5/18 — Principles 2 Plan for Success", "5/18 — Clinical Airway Anatomy Workbook", "Clinical: Tues/Wed"] },
  { week: "Week of 5/18", focus: "Systems + first recurring clinical workflow", tasks: ["5/20 — Systems Intro Discussion Board", "5/20 or 5/21 — Optional SIM Adductor Canal & Popliteal", "5/22 — Systems Assignment 1", "5/23 — Systems Discussion Board 1", "5/25 — Clinical Week 2: 2 evals + 2 care plans", "5/26 — Plagiarism Attestation Quiz", "5/30 — Systems Discussion Board Replies", "Clinical: Tues/Wed"] },
  { week: "Week of 6/1", focus: "Respiratory block + Exam 1 prep", tasks: ["6/1 — Clinical Respiratory Physiology WB + evals/care plans", "Week of 6/1 — Seminar Presentation 1 or discussion alternative", "6/3 or 6/4 — SIM Optional LAST/Pneumoperitoneum/Machine Failure", "6/6 — Systems Discussion Board 2", "6/8 — Principles 2 Exam 1", "6/8 — Clinical Respiratory Pathophys WB + evals/care plans", "Clinical: Tues/Wed until switch on 6/8"] },
  { week: "Week of 6/15", focus: "Airway + journal club + SIM test-out prep", tasks: ["Week of 6/15 — Seminar Presentation 2 or discussion alternative", "6/15 — Clinical Airway Management WB + evals/care plans", "6/15 — Mandatory Journal Club Session TBD", "6/22 — Clinical Cell Communication WB", "6/22 — Comprehensive Care Plan #1", "6/24 or 6/25 — Mandatory SIM Test-Out Class", "Clinical: Thurs/Fri"] },
  { week: "Week of 7/6", focus: "ANS + Exam 2", tasks: ["7/2 — SIM Bronchospasm/Anaphylaxis Quiz", "7/6 — Clinical ANS Anatomy & Physiology WB + evals/care plans", "7/6 — Summative Evals + Preceptor/Site Evals", "7/9 — SIM Hypoxia Quiz", "7/11 — Systems DB 3, no peer responses", "7/13 — Principles 2 AP2 Exam 2", "7/13 — Clinical ANS Pharm & Patho WB + evals/care plans", "Clinical: Tues/Wed"] },
  { week: "Week of 7/20", focus: "Cardiac-heavy stretch", tasks: ["7/19 — SIM Discussion Board #1", "7/20 — Clinical Cardiovascular Anatomy & Physiology WB + evals/care plans", "7/20 — Seminar Franciscan Values Paper", "Week of 7/20 — Seminar Presentation 4 or discussion alternative", "7/25 — Systems Assignment 2", "7/27 — Clinical Valvular Heart Disease WB + evals/care plans", "7/27 — Mandatory Journal Club Session TBD", "Clinical: Tues/Wed until 7/27 switch, then Thurs/Fri"] },
  { week: "Week of 8/3", focus: "Final stretch", tasks: ["8/2 — SIM Discussion Board #2", "8/3 — Clinical Cardiovascular Pathophys WB + evals/care plans", "Week of 8/3 — Seminar Presentation 5 or discussion alternative", "8/10 — Principles 2 Exam 3", "8/10 — Clinical Comprehensive Care Plan #2 + evals/care plans", "Week of 8/10 — Seminar Quiz 2", "8/11 — Systems Professional Practice Paper", "8/17 — Principles 2 AP2 Final Exam + clinical make-up week items", "Clinical: Thurs/Fri through 8/14"] },
];

const starterAssignments = [
  [1,"2026-05-15","Intro Discussion Board","Seminar 1","5/15","High","Professional bio discussion board"],[2,"2026-05-15","Syllabus Attestation","Clinical","5/15","Critical","Clinical syllabus attestation"],[3,"2026-05-17","Syllabus Review Attestation","SIM","5/17","Critical","SIM syllabus review attestation"],[4,"2026-05-18","Syllabus Attestation Quiz","Seminar 1","5/18","Critical","Required quiz"],[5,"2026-05-18","Plan for Success","Principles 2","5/18","High","Principles 2 assignment"],[6,"2026-05-18","Airway Anatomy WB","Clinical","5/18","High","Workbook"],[7,"2026-05-20","Intro Discussion Board","Systems","5/20","High","Systems intro discussion"],[8,"2026-05-20","Optional Class: Adductor Canal & Popliteal Canal","SIM","5/20 or 5/21","Low","Optional class"],[9,"2026-05-22","Assignment 1","Systems","5/22","High","Systems assignment"],[10,"2026-05-23","Discussion Board 1","Systems","5/23","High","Initial discussion board post"],[11,"2026-05-25","Week 2: 2 Clinical Evals + 2 Weekly Care Plans","Clinical","5/25","Critical","Recurring clinical paperwork"],[12,"2026-05-26","Plagiarism Attestation Quiz","Systems","5/26","Critical","Required attestation quiz"],[13,"2026-05-30","Discussion Board Replies","Systems","5/30","High","Peer replies"],
  [14,"2026-06-01","Respiratory Physiology WB","Clinical","6/1","High","Workbook"],[15,"2026-06-01","2 Clinical Evals + 2 Weekly Care Plans","Clinical","6/1","Critical","Recurring clinical paperwork"],[16,"2026-06-01","Student Presentation 1 / Optional Live or Discussion Post","Seminar 1","Week of 6/1","Medium","Attend optional live or complete discussion post"],[17,"2026-06-03","Optional Class: LAST, Pneumoperitoneum, Anesthesia Machine Failure","SIM","6/3 or 6/4","Low","Optional SIM class"],[18,"2026-06-06","Discussion Board 2","Systems","6/6","High","Systems discussion board"],[19,"2026-06-08","EXAM 1","Principles 2","6/8","Critical","Principles 2 exam"],[20,"2026-06-08","Respiratory Pathophys WB","Clinical","6/8","High","Workbook"],[21,"2026-06-08","2 Clinical Evals + 2 Weekly Care Plans","Clinical","6/8","Critical","Recurring clinical paperwork"],[22,"2026-06-13","Discussion Board Replies","Systems","6/13","High","Peer replies"],[23,"2026-06-15","Student Presentation 2 / Optional Live or Discussion Post","Seminar 1","Week of 6/15","Medium","Attend optional live or complete discussion post"],[24,"2026-06-15","Airway Management WB","Clinical","6/15","High","Workbook"],[25,"2026-06-15","Mandatory Journal Club Session","Clinical","TBD","Critical","Listed near 6/15 on due date calendar"],[26,"2026-06-15","2 Clinical Evals + 2 Weekly Care Plans","Clinical","6/15","Critical","Recurring clinical paperwork"],[27,"2026-06-22","Cell Communication WB","Clinical","6/22","High","Workbook"],[28,"2026-06-22","Comprehensive Care Plan #1","Clinical","6/22","Critical","Major assignment"],[29,"2026-06-22","2 Clinical Evals + 2 Weekly Care Plans","Clinical","6/22","Critical","Recurring clinical paperwork"],[30,"2026-06-24","Mandatory Classes in Indy / Test-Out Week","SIM","6/24 or 6/25","Critical","Epidural, spinal, interscalene, adductor canal, popliteal, LAST, pneumoperitoneum, anesthesia machine failure"],[31,"2026-06-29","Student Presentation 3 / Optional Live or Discussion Post","Seminar 1","Week of 6/29","Medium","Attend optional live or complete discussion post"],
  [32,"2026-07-02","Bronchospasm/Anaphylaxis Quiz","SIM","7/2","High","SIM quiz"],[33,"2026-07-06","ANS Anatomy & Physiology WB","Clinical","7/6","High","Workbook"],[34,"2026-07-06","2 Clinical Evals + 2 Weekly Care Plans","Clinical","7/6","Critical","Recurring clinical paperwork"],[35,"2026-07-06","Summative Evals + Evals of Preceptors & Site","Clinical","7/6","Critical","End-of-rotation evaluation items"],[36,"2026-07-09","Hypoxia Quiz","SIM","7/9","High","SIM quiz"],[37,"2026-07-11","Discussion Board 3 — No Peer Responses","Systems","7/11","High","No peer responses"],[38,"2026-07-13","AP2: EXAM 2","Principles 2","7/13","Critical","Principles 2 exam"],[39,"2026-07-13","ANS Pharm & Patho WB","Clinical","7/13","High","Workbook"],[40,"2026-07-13","2 Clinical Evals + 2 Weekly Care Plans","Clinical","7/13","Critical","Recurring clinical paperwork"],[41,"2026-07-13","Quiz 1 over Student Presentations 1–3","Seminar 1","Week of 7/13","High","Seminar quiz"],[42,"2026-07-19","Discussion Board #1","SIM","7/19","Medium","SIM discussion board"],[43,"2026-07-20","Cardiovascular Anatomy & Physiology WB","Clinical","7/20","High","Workbook"],[44,"2026-07-20","2 Clinical Evals + 2 Weekly Care Plans","Clinical","7/20","Critical","Recurring clinical paperwork"],[45,"2026-07-20","Franciscan Values Paper","Seminar 1","7/20","High","Paper"],[46,"2026-07-20","Student Presentation 4 / Optional Live or Discussion Post","Seminar 1","Week of 7/20","Medium","Attend optional live or complete discussion post"],[47,"2026-07-25","Assignment 2","Systems","7/25","High","Systems assignment"],[48,"2026-07-27","Valvular Heart Dz WB","Clinical","7/27","High","Workbook"],[49,"2026-07-27","Mandatory Journal Club Session","Clinical","TBD","Critical","Listed near 7/27 on due date calendar"],[50,"2026-07-27","2 Clinical Evals + 2 Weekly Care Plans","Clinical","7/27","Critical","Recurring clinical paperwork"],
  [51,"2026-08-02","Discussion Board #2","SIM","8/2","Medium","SIM discussion board"],[52,"2026-08-03","Cardiovascular Pathophys WB","Clinical","8/3","High","Workbook"],[53,"2026-08-03","2 Clinical Evals + 2 Weekly Care Plans","Clinical","8/3","Critical","Recurring clinical paperwork"],[54,"2026-08-03","Student Presentation 5 / Optional Live or Discussion Post","Seminar 1","Week of 8/3","Medium","Attend optional live or complete discussion post"],[55,"2026-08-10","EXAM 3","Principles 2","8/10","Critical","Principles 2 exam"],[56,"2026-08-10","Comprehensive Care Plan #2","Clinical","8/10","Critical","Major assignment"],[57,"2026-08-10","2 Clinical Evals + 2 Weekly Care Plans","Clinical","8/10","Critical","Recurring clinical paperwork"],[58,"2026-08-10","Quiz 2 over Student Presentations 4 & 5","Seminar 1","Week of 8/10","High","Seminar quiz"],[59,"2026-08-11","Professional Practice Paper","Systems","8/11","High","Systems paper"],[60,"2026-08-17","Finals Week","University Days to Know","8/17–8/21","High","Finals week"],[61,"2026-08-17","AP2 Final Exam","Principles 2","8/17","Critical","Final exam"],[62,"2026-08-17","Clinical Make-Up Week","Clinical","8/17","High","Clinical make-up week"],[63,"2026-08-17","Summative Evals + Evals of Preceptors & Site","Clinical","8/17","Critical","Final clinical evaluation items"]
].map(([id, sortDate, assignment, course, due, priority, notes]) => ({ id, sortDate, assignment, course, due, status: "Not Started", priority, notes }));

const clinicalChecks = ["Patient lookup completed", "Airway concerns reviewed", "Anesthetic plan drafted", "Meds/pressors reviewed", "Clinical eval submitted", "Medatrax updated", "Care-plan-worthy case flagged", "Things to review saved"];
const statusOptions = ["Not Started", "In Progress", "Waiting", "Submitted", "Complete"];
const priorityOptions = ["Critical", "High", "Medium", "Low"];
const courseOptions = ["All", "Active", "Critical", "Seminar 1", "Clinical", "SIM", "Systems", "Principles 2", "University Days to Know"];

function getFilteredAssignments(assignments, filter) { if (filter === "All") return assignments; if (filter === "Active") return assignments.filter(a => a.status !== "Complete" && a.status !== "Submitted"); if (filter === "Critical") return assignments.filter(a => a.priority === "Critical"); return assignments.filter(a => a.course === filter); }
function getCompletionPercent(assignments) { if (!assignments.length) return 0; return Math.round(assignments.filter(a => a.status === "Complete" || a.status === "Submitted").length / assignments.length * 100); }
function buildCalendarCells(month) { const cells = []; for (let i = 0; i < month.start; i++) cells.push(null); for (let d = 1; d <= month.days; d++) cells.push(d); while (cells.length % 7) cells.push(null); return cells; }
function Badge({ children, tone = "slate" }) { const tones = { slate: "bg-slate-100 text-slate-700", red: "bg-red-100 text-red-700", orange: "bg-orange-100 text-orange-700", green: "bg-green-100 text-green-700", blue: "bg-blue-100 text-blue-700", purple: "bg-purple-100 text-purple-700", yellow: "bg-yellow-100 text-yellow-800" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone] || tones.slate}`}>{children}</span>; }
function Card({ children, className = "" }) { return <div className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>; }
function ActionButton({ children, onClick, variant = "primary", className = "" }) { const variants = { primary: "bg-slate-900 text-white hover:bg-slate-700", secondary: "border border-slate-300 bg-white text-slate-800 hover:bg-slate-100", danger: "text-red-600 hover:bg-red-50" }; return <button type="button" onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold transition ${variants[variant]} ${className}`}>{children}</button>; }
function TextInput(props) { return <input {...props} className={`w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-200 ${props.className || ""}`} />; }
function TextArea(props) { return <textarea {...props} className={`min-h-[92px] w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-200 ${props.className || ""}`} />; }
function SelectBox({ value, onChange, options }) { return <select value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">{options.map(o => <option key={o} value={o}>{o}</option>)}</select>; }
function getPriorityTone(p) { return p === "Critical" ? "red" : p === "High" ? "orange" : p === "Medium" ? "blue" : "green"; }
function getEventTone(event) { if (event.includes("Clinical")) return "border-green-200 bg-green-100 text-green-800"; if (event.includes("EXAM") || event.includes("Exam") || event.includes("Quiz") || event.includes("Final")) return "border-red-200 bg-red-100 text-red-800"; if (event.includes("SIM")) return "border-blue-200 bg-blue-100 text-blue-800"; if (event.includes("Seminar")) return "border-orange-200 bg-orange-100 text-orange-800"; if (event.includes("Systems")) return "border-yellow-200 bg-yellow-100 text-yellow-800"; if (event.includes("WB") || event.includes("care plans")) return "border-purple-200 bg-purple-100 text-purple-800"; return "border-slate-200 bg-white text-slate-700"; }
function makeEventId(m, d, e, i) { return `${m}-${d}-${i}-${e}`; }
const STORAGE_KEY = "srna-command-center-summer-2026-v1";
function loadSavedState() { try { const raw = localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) : null; } catch { return null; } }
function saveState(state) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); return true; } catch { return false; } }
function clearSavedState() { try { localStorage.removeItem(STORAGE_KEY); return true; } catch { return false; } }
function mergeAssignmentsWithDefaults(saved) { if (!Array.isArray(saved)) return starterAssignments; const savedById = new Map(saved.map(i => [i.id, i])); const merged = starterAssignments.map(i => ({ ...i, ...(savedById.get(i.id) || {}) })); const ids = new Set(starterAssignments.map(i => i.id)); return [...merged, ...saved.filter(i => !ids.has(i.id))].sort((a,b)=>String(a.sortDate||"9999").localeCompare(String(b.sortDate||"9999"))); }
function buildPlannerState(s) { return s; }
function downloadPlannerBackup(data) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `srna-planner-backup-${new Date().toISOString().split("T")[0]}.json`; a.click(); URL.revokeObjectURL(url); }
async function importPlannerBackup(file) { try { return JSON.parse(await file.text()); } catch { return null; } }
async function safeCopy(text) { try { await navigator.clipboard.writeText(text); return true; } catch { return false; } }
function makeAssignmentExportText(a) { return a.map(x => `${x.course} | ${x.assignment} | Due: ${x.due} | Status: ${x.status} | Priority: ${x.priority}`).join("\n"); }
function makeBrainDumpText(list) { return list.map(x=>x.trim()).filter(Boolean).map((x,i)=>`${i+1}. ${x}`).join("\n"); }
function makeClinicalTemplateText(clinical, checked) { return `CLINICAL DAY TEMPLATE\nDate: ${clinical.date}\nSite: ${clinical.site}\nPreceptor: ${clinical.preceptor}\n\nCases:\n${clinical.cases}\n\nAirway/Anesthesia Concerns:\n${clinical.airway}\n\nMeds/Pressors/Fluids:\n${clinical.meds}\n\nLearning Points:\n${clinical.learning}\n\nThings to Review:\n${clinical.review}\n\nCompleted Checklist:\n${Object.keys(checked).filter(k=>checked[k]).map(k=>`- ${k}`).join("\n")}`; }

export default function App() {
  const savedState = useMemo(() => loadSavedState(), []);
  const [assignments, setAssignments] = useState(() => mergeAssignmentsWithDefaults(savedState?.assignments));
  const [filter, setFilter] = useState(savedState?.filter || "All");
  const [activeTab, setActiveTab] = useState(savedState?.activeTab || "calendar");
  const [newAssignment, setNewAssignment] = useState({ assignment: "", course: "Clinical", due: "", priority: "Medium", status: "Not Started", notes: "" });
  const [clinical, setClinical] = useState(savedState?.clinical || { date: "", site: "", preceptor: "", cases: "", airway: "", meds: "", learning: "", review: "" });
  const [checked, setChecked] = useState(savedState?.checked || {});
  const [calendarChecked, setCalendarChecked] = useState(savedState?.calendarChecked || {});
  const [weeklyChecked, setWeeklyChecked] = useState(savedState?.weeklyChecked || {});
  const [brainDump, setBrainDump] = useState(savedState?.brainDump || ["", "", "", "", ""]);
  const [copyMessage, setCopyMessage] = useState(savedState ? "Loaded saved planner progress from this browser." : "");
  const [cloudStatus, setCloudStatus] = useState("Connecting to Firebase...");
  const [cloudLoaded, setCloudLoaded] = useState(false);
  const filteredAssignments = useMemo(() => getFilteredAssignments(assignments, filter), [assignments, filter]);
  const completion = getCompletionPercent(assignments);
  const activeCount = getFilteredAssignments(assignments, "Active").length;
  const criticalCount = getFilteredAssignments(assignments, "Critical").filter(a => a.status !== "Complete" && a.status !== "Submitted").length;
  const calendarItemCount = Object.keys(calendarChecked).filter(k => calendarChecked[k]).length;

  useEffect(() => { let live = true; (async () => { try { const snap = await getDoc(PLANNER_DOC_REF); if (!live) return; if (snap.exists()) { const c = snap.data(); setAssignments(mergeAssignmentsWithDefaults(c.assignments || [])); setFilter(c.filter || "All"); setActiveTab(c.activeTab || "calendar"); setClinical(c.clinical || { date: "", site: "", preceptor: "", cases: "", airway: "", meds: "", learning: "", review: "" }); setChecked(c.checked || {}); setCalendarChecked(c.calendarChecked || {}); setWeeklyChecked(c.weeklyChecked || {}); setBrainDump(c.brainDump || ["", "", "", "", ""]); setCloudStatus("Cloud sync connected. Loaded from Firebase."); } else setCloudStatus("Cloud sync connected. This device will create your planner."); } catch(e) { console.warn(e); setCloudStatus("Firebase connection failed. Check Firestore rules. Local autosave still works."); } finally { if(live) setCloudLoaded(true); } })(); return () => { live = false; }; }, []);
  useEffect(() => { const state = buildPlannerState({ assignments, filter, activeTab, clinical, checked, calendarChecked, weeklyChecked, brainDump }); saveState({ ...state, savedAt: new Date().toISOString() }); if (!cloudLoaded) return; const t = setTimeout(async () => { try { await setDoc(PLANNER_DOC_REF, { ...state, updatedAt: serverTimestamp() }, { merge: true }); setCloudStatus("Cloud sync saved."); } catch(e) { console.warn(e); setCloudStatus("Cloud sync failed. Check Firestore rules. Local autosave still works."); } }, 900); return () => clearTimeout(t); }, [assignments, filter, activeTab, clinical, checked, calendarChecked, weeklyChecked, brainDump, cloudLoaded]);

  const updateAssignment = (id, field, value) => setAssignments(cur => cur.map(a => a.id === id ? { ...a, [field]: value } : a));
  const addAssignment = () => { if (!newAssignment.assignment.trim()) return setCopyMessage("Add an assignment name first."); setAssignments(cur => [{ id: Date.now(), sortDate: "9999-99-99", ...newAssignment, assignment: newAssignment.assignment.trim() }, ...cur]); setNewAssignment({ assignment: "", course: "Clinical", due: "", priority: "Medium", status: "Not Started", notes: "" }); };
  const handleCopy = async (text, msg) => setCopyMessage(await safeCopy(text) ? msg : "Copy failed; select manually.");
  const exportPlanner = () => { downloadPlannerBackup({ assignments, filter, activeTab, clinical, checked, calendarChecked, weeklyChecked, brainDump, exportedAt: new Date().toISOString() }); setCopyMessage("Planner backup downloaded."); };
  const handleImportPlanner = async e => { const file = e.target.files?.[0]; if (!file) return; const imported = await importPlannerBackup(file); if (!imported) return setCopyMessage("Unable to import backup."); setAssignments(mergeAssignmentsWithDefaults(imported.assignments || [])); setFilter(imported.filter || "All"); setActiveTab(imported.activeTab || "calendar"); setClinical(imported.clinical || {}); setChecked(imported.checked || {}); setCalendarChecked(imported.calendarChecked || {}); setWeeklyChecked(imported.weeklyChecked || {}); setBrainDump(imported.brainDump || ["", "", "", "", ""]); setCopyMessage("Planner backup imported."); };
  const resetSavedPlanner = () => { clearSavedState(); setAssignments(starterAssignments); setFilter("All"); setActiveTab("calendar"); setClinical({ date:"", site:"", preceptor:"", cases:"", airway:"", meds:"", learning:"", review:"" }); setChecked({}); setCalendarChecked({}); setWeeklyChecked({}); setBrainDump(["", "", "", "", ""]); setCopyMessage("Saved progress cleared."); };

  return <div className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">Summer 2026</p><h1 className="text-3xl font-bold tracking-tight md:text-5xl">SRNA Command Center</h1><p className="mt-2 max-w-2xl text-slate-600">Interactive calendar, assignment list, clinical template, and weekly brain dump. Autosaves locally and syncs to Firebase.</p></div><div className="grid grid-cols-4 gap-3 md:w-[600px]"><Card className="p-4"><div className="text-xs text-slate-500">Assignments</div><div className="mt-1 text-2xl font-bold">{completion}%</div></Card><Card className="p-4"><div className="text-xs text-slate-500">Active</div><div className="mt-1 text-2xl font-bold">{activeCount}</div></Card><Card className="p-4"><div className="text-xs text-slate-500">Critical</div><div className="mt-1 text-2xl font-bold">{criticalCount}</div></Card><Card className="p-4"><div className="text-xs text-slate-500">Calendar Done</div><div className="mt-1 text-2xl font-bold">{calendarItemCount}</div></Card></div></header>
    {copyMessage && <div className="rounded-xl border bg-white p-3 text-sm shadow-sm">{copyMessage}</div>}
    <Card className="p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="text-sm font-bold">Autosave + Firebase sync</div><div className="text-xs text-slate-600">{cloudStatus}</div></div><div className="flex flex-wrap gap-2"><ActionButton variant="secondary" onClick={exportPlanner}>Export backup</ActionButton><label className="inline-flex cursor-pointer items-center justify-center rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-semibold hover:bg-slate-100">Import backup<input type="file" accept="application/json" className="hidden" onChange={handleImportPlanner} /></label><ActionButton variant="secondary" onClick={resetSavedPlanner}>Reset saved progress</ActionButton></div></div></Card>
    <nav className="grid grid-cols-5 gap-2 rounded-2xl bg-slate-200 p-1 md:w-[920px]">{[{key:"calendar",label:"📅 Calendar"},{key:"schedule",label:"🗓 Weekly Plan"},{key:"assignments",label:"☑ Assignments"},{key:"clinical",label:"🩺 Clinical"},{key:"brain",label:"🧠 Brain Dump"}].map(tab=><button key={tab.key} onClick={()=>setActiveTab(tab.key)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${activeTab===tab.key?"bg-white shadow-sm":"text-slate-600 hover:bg-slate-100"}`}>{tab.label}</button>)}</nav>

    {activeTab === "calendar" && <section className="space-y-8"><Card className="p-5"><div className="flex justify-between gap-2"><div><h2 className="text-2xl font-bold">Interactive Semester Calendar</h2><p className="text-sm text-slate-600">Checkboxes are built into each clinical day and assignment.</p></div><ActionButton variant="secondary" onClick={()=>setCalendarChecked({})}>Clear calendar checks</ActionButton></div></Card>{calendarMonths.map(month => { const info=monthlyCalendarData[month.name]; const cells=buildCalendarCells(month); return <Card key={month.name} className={`overflow-hidden border-0 bg-gradient-to-br ${info.color}`}><div className="p-6 md:p-8"><div className="mb-6 flex justify-between gap-3"><div><div className={`text-6xl font-black opacity-70 md:text-8xl ${info.accent}`}>2026</div><h2 className="-mt-6 text-4xl font-light italic md:text-6xl">{month.name}</h2></div><div className="grid grid-cols-2 gap-2 self-end text-xs md:grid-cols-3"><Badge tone="orange">Seminar/Principles</Badge><Badge tone="blue">SIM</Badge><Badge tone="green">Clinical</Badge><Badge tone="purple">WB/Care Plan</Badge><Badge tone="red">Exams/Quizzes</Badge></div></div><div className="grid grid-cols-7 gap-2 text-center text-xs font-bold uppercase text-slate-500">{weekdayHeaders.map(d=><div key={d} className="py-2">{d}</div>)}</div><div className="grid grid-cols-7 gap-2">{cells.map((day,index)=>{ const events=day?[...(clinicalSchedule[month.name]?.[day]||[]),...(info.events[day]||[])]:[]; return <div key={`${month.name}-${index}`} className={`min-h-[130px] rounded-2xl border border-white/60 bg-white/60 p-2 md:min-h-[165px] ${events.length?"shadow-sm":"opacity-70"}`}>{day&&<><div className="mb-2 text-right text-sm font-bold md:text-base">{day}</div><div className="space-y-1">{events.map((event,i)=>{ const id=makeEventId(month.name,day,event,i); const done=!!calendarChecked[id]; return <label key={id} className={`flex cursor-pointer items-start gap-1.5 rounded-lg border px-2 py-1 text-[10px] font-medium leading-tight md:text-xs ${getEventTone(event)} ${done?"opacity-55 line-through":""}`}><input type="checkbox" checked={done} onChange={e=>setCalendarChecked({...calendarChecked,[id]:e.target.checked})} className="mt-0.5 h-3 w-3 shrink-0"/><span>{event}</span></label>})}</div></>}</div>})}</div></div></Card>})}</section>}

    {activeTab === "schedule" && <section className="space-y-4"><Card className="p-5"><h2 className="text-2xl font-bold">Week-by-Week Survival Plan</h2><p className="text-sm text-slate-600">Grouped by workload so you can plan ahead.</p></Card>{weeklySchedule.map((week,wi)=><Card key={week.week} className="p-5"><h3 className="text-xl font-bold">{week.week}</h3><p className="text-sm text-slate-600">{week.focus}</p><div className="mt-4 space-y-2">{week.tasks.map((task,i)=>{ const id=`${wi}-${i}-${task}`; const done=!!weeklyChecked[id]; return <label key={id} className={`flex cursor-pointer items-start gap-3 rounded-xl border bg-slate-50 p-3 ${done?"opacity-55 line-through":""}`}><input type="checkbox" checked={done} onChange={e=>setWeeklyChecked({...weeklyChecked,[id]:e.target.checked})} className="mt-1 h-4 w-4"/><span className="text-sm">{task}</span></label>})}</div></Card>)}</section>}

    {activeTab === "assignments" && <section className="space-y-4"><Card className="p-4"><h2 className="mb-3 text-xl font-bold">Add assignment</h2><div className="grid gap-3 md:grid-cols-6"><TextInput className="md:col-span-2" placeholder="Assignment" value={newAssignment.assignment} onChange={e=>setNewAssignment({...newAssignment,assignment:e.target.value})}/><SelectBox value={newAssignment.course} onChange={v=>setNewAssignment({...newAssignment,course:v})} options={courseOptions.filter(x=>!["All","Active","Critical"].includes(x))}/><TextInput placeholder="Due date" value={newAssignment.due} onChange={e=>setNewAssignment({...newAssignment,due:e.target.value})}/><SelectBox value={newAssignment.priority} onChange={v=>setNewAssignment({...newAssignment,priority:v})} options={priorityOptions}/><ActionButton onClick={addAssignment}>+ Add</ActionButton></div><TextInput className="mt-3" placeholder="Notes" value={newAssignment.notes} onChange={e=>setNewAssignment({...newAssignment,notes:e.target.value})}/></Card><div className="flex flex-wrap gap-2">{courseOptions.map(f=><ActionButton key={f} variant={filter===f?"primary":"secondary"} className="rounded-full" onClick={()=>setFilter(f)}>{f}</ActionButton>)}<ActionButton variant="secondary" className="rounded-full" onClick={()=>handleCopy(makeAssignmentExportText(filteredAssignments),"Assignment list copied.")}>Copy visible list</ActionButton></div><div className="grid gap-3">{filteredAssignments.map(a=><Card key={a.id} className="p-4"><div className="grid gap-3 md:grid-cols-12 md:items-center"><div className="md:col-span-3"><TextInput value={a.assignment} onChange={e=>updateAssignment(a.id,"assignment",e.target.value)}/></div><div className="md:col-span-1"><Badge>{a.course}</Badge></div><div className="md:col-span-2"><TextInput value={a.due} onChange={e=>updateAssignment(a.id,"due",e.target.value)}/></div><div className="md:col-span-2"><SelectBox value={a.status} onChange={v=>updateAssignment(a.id,"status",v)} options={statusOptions}/></div><div className="md:col-span-1"><Badge tone={getPriorityTone(a.priority)}>{a.priority}</Badge></div><div className="md:col-span-2"><TextInput value={a.notes} onChange={e=>updateAssignment(a.id,"notes",e.target.value)}/></div><ActionButton variant="danger" onClick={()=>setAssignments(cur=>cur.filter(x=>x.id!==a.id))}>×</ActionButton></div></Card>)}</div></section>}

    {activeTab === "clinical" && <section><Card className="p-5"><div className="mb-4 flex justify-between gap-2"><div><h2 className="text-2xl font-bold">Clinical Day Template</h2><p className="text-sm text-slate-600">Patient lookup and post-clinical notes.</p></div><ActionButton onClick={()=>handleCopy(makeClinicalTemplateText(clinical,checked),"Clinical note copied.")}>Copy clinical note</ActionButton></div><div className="grid gap-3 md:grid-cols-3"><TextInput placeholder="Date" value={clinical.date} onChange={e=>setClinical({...clinical,date:e.target.value})}/><TextInput placeholder="Site" value={clinical.site} onChange={e=>setClinical({...clinical,site:e.target.value})}/><TextInput placeholder="Preceptor" value={clinical.preceptor} onChange={e=>setClinical({...clinical,preceptor:e.target.value})}/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><TextArea placeholder="Cases / procedures" value={clinical.cases} onChange={e=>setClinical({...clinical,cases:e.target.value})}/><TextArea placeholder="Airway + anesthesia concerns" value={clinical.airway} onChange={e=>setClinical({...clinical,airway:e.target.value})}/><TextArea placeholder="Meds, pressors, fluids, local anesthetics" value={clinical.meds} onChange={e=>setClinical({...clinical,meds:e.target.value})}/><TextArea placeholder="Learning points / preceptor pearls" value={clinical.learning} onChange={e=>setClinical({...clinical,learning:e.target.value})}/></div><TextArea className="mt-3" placeholder="Things to review later" value={clinical.review} onChange={e=>setClinical({...clinical,review:e.target.value})}/><h3 className="mt-5 text-lg font-bold">Quick checklist</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{clinicalChecks.map(item=><label key={item} className="flex cursor-pointer items-center gap-3 rounded-xl border bg-slate-50 p-3 text-sm"><input type="checkbox" checked={!!checked[item]} onChange={e=>setChecked({...checked,[item]:e.target.checked})} className="h-4 w-4"/><span>{item}</span></label>)}</div></Card></section>}

    {activeTab === "brain" && <section><Card className="p-5"><div className="mb-4 flex justify-between gap-2"><div><h2 className="text-2xl font-bold">Weekly Brain Dump</h2><p className="text-sm text-slate-600">Get it out of your head before you forget it.</p></div><ActionButton onClick={()=>handleCopy(makeBrainDumpText(brainDump),"Brain dump copied.")}>Copy brain dump</ActionButton></div><div className="space-y-3">{brainDump.map((item,i)=><TextInput key={i} placeholder={`Brain dump item ${i+1}`} value={item} onChange={e=>{const next=[...brainDump]; next[i]=e.target.value; setBrainDump(next)}}/>)}</div><div className="mt-4 flex gap-2"><ActionButton variant="secondary" onClick={()=>setBrainDump(cur=>[...cur,""])}>Add line</ActionButton><ActionButton variant="secondary" onClick={()=>setBrainDump(["","","","",""])}>Clear</ActionButton></div></Card></section>}
  </div></div>;
}
